### ISSUE TITLE
Possibility of limiting max *input* pressure?

### ISSUE THREAD

**Issue by RavenmoreGIT** [Kuuuube/Slimy_Scylla#1]
I love the plugin so far =)

Wondering if there's a chance to add limiting the max input pressure.
It's a feature Huion and quite a few other tablets lack, that makes a world of difference for artists (less max pressure needed = healthier wrists). 

So the desired outcome would be I press at 70% input, and the output is 100%. Everything else is interpolated between those values.

**Comment by Kuuuube** [comment]
This is already implemented. Use the pressure curve filter https://github.com/Kuuuube/Slimy_Scylla/blob/main/docs/pressure_curve/pressure_curve.md.

With gain set to 1.43 and everything else default this looks like it will do what you want 
![image](https://github.com/Kuuuube/Slimy_Scylla/assets/61125188/9b9b2370-a199-4f42-a859-814a595c9c8d)

**Comment by RavenmoreGIT** [comment]
Thank youuuu! Sorry, was unaware Gain is the correct term. This is exactly what I needed, awesome!
