### ISSUE TITLE
Flickering and teleporting Cursor

### ISSUE THREAD

**Issue by YoelNath** [Kuuuube/Slimy_Scylla#2]
Hi, im currently using only this configuration for the smoothing, but the cursor seems to be teleporting or flickering infrequently and i cannot figure out why(i will record the problem if you want me to, but it happen so randomly when i tried to record it for 5 minutes it doesnt happen at all), i already unplugged my mouse and the it still happens, the pen tablet im using is VEIKK A30 V2 and im only using the windows ink absolute mode plugin with this plugin can you help me?
![{13A8D355-D428-4F98-B102-B4197A5C909F}](https://github.com/user-attachments/assets/c855a4fd-f1f2-4ae3-9aef-be3f7da65449)

**Comment by Kuuuube** [comment]
A recording would be helpful, yes. When you record this, record otd's debugger as well. `tablets > tablet debugger`  from the top menu.

Also make sure no other tablet drivers are present by running this <https://github.com/X9VoiD/TabletDriverCleanup/releases/latest>.

And it is likely your tablet could be getting teleporting if you are accidentally pressing the pen side buttons. That may be why it seems random.

**Comment by YoelNath** [comment]
sorry, after i tried your solution of using the tablet driver cleanup there seems to be no more flickering or teleporting for a few days, thanks for the help
